# Generated by Django 5.2.7 on 2026-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_town',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
