# Generated by Django 5.2.7 on 2025-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_rename_date_subimtted_issue_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='course',
            field=models.CharField(default='No Course', max_length=100),
        ),
    ]
