# Generated by Django 5.2.7 on 2026-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_issue_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='course',
        ),
        migrations.AddField(
            model_name='issue',
            name='module',
            field=models.CharField(default='No Module', max_length=100),
        ),
    ]
