# Generated by Django 5.2.7 on 2026-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_remove_issue_course_issue_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='course',
            field=models.CharField(choices=[('Cyber Security', 'Cyber Security'), ('Smart Computing', 'Smart Computing'), ('Computer Science', 'Computer Science')], default='No Course', max_length=100),
        ),
    ]
