# Generated by Django 5.2.7 on 2026-01-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_remove_issue_type_issue_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.CharField(max_length=100),
        ),
    ]
