# Generated by Django 5.2.7 on 2026-01-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0006_alter_issue_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='details',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='urgent',
        ),
    ]
