# Generated by Django 5.2.7 on 2026-01-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0007_remove_issue_details_remove_issue_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='availability',
            field=models.CharField(choices=[('Open for Registration', 'Open for Registration'), ('Closed for Registration', 'Closed for Registration')], default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='code',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='courses_allowed_to_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
