# Generated by Django 5.2.7 on 2026-01-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0008_issue_availability_issue_category_issue_code_and_more'),
        ('users', '0004_profile_address_profile_city_town_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='itreporting.issue')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.profile')),
            ],
            options={
                'ordering': ['-date_registered'],
                'unique_together': {('profile', 'issue')},
            },
        ),
    ]
